server:
  port: 8002
spring:
  application:
    name: cloud-payment-service
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/database1?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
      username: root
      password: 123456



mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.zdw.springcloud.entities

eureka:
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
    instance:
      instance-id: payment8002
      prefer-ip-address: true