server:
  port: 9001  #服务端口号

spring:
  application:
    name: nacos-payment-provider   # 也是注册到 nacos 服务的名称( 服务别名(使用服务别名去注册中心获取实际的RPC远程调用地址) )
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'